name: Hystreet
markdown: kramdown
# pygments: true
highlighter: true
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
collections:
  - releases
tipue_search:
  include:
    pages: true
gems: [jekyll-paginate]
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - circle.yml
