name: Hystreet
markdown: redcarpet
highlighter: pygments
plugins: [jekyll-paginate-v2]
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - circle.yml
  - doc

excerpt_separator: <!--more-->

collections:
  releases:
    output: true

permalink: /:categories/:title

pagination:
  enabled: true
  debug: true
  per_page: 3

algolia:
  application_id: 6WV9RIWWJC
  index_name: learninghub # You can replace that with whatever name you want
  search_only_api_key: 77a29259d33de9e1ff34c4676e00ee17
  files_to_exclude:
    - _releases/*
    - _posts/*
    - coming-soon/*
    - index.html
    - guides/index.html
    - guides/appointments/index.html
    - guides/buyer/index.html
    - guides/getting-started-with-hystreet/index.html
    - guides/models/index.html
    - guides/portal-setup/index.html
    - guides/seller/index.html
    - guides/setting-up-stripe/index.html
    - guides/staff-site/index.html
    - guides/your-website/index.html
    - faqs/index.html
